name: Deploy Realm App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # You can choose the Node.js version

    - name: Install TypeScript
      run: npm install -g typescript

    - name: Install AppServices Package
      run: npm install appservices

    - name: Login to AppServices
      env: 
        REALM_PUBLIC_KEY: ${{secrets.REALM_PUBLIC_KEY}}
        REALM_PRIVATE_KEY: ${{secrets.REALM_PRIVATE_KEY}}
      run: appservices login --api-key REALM_PUBLIC_KEY --private-api-key REALM_PRIVATE_KEY
    - name: Push to AppServices
      env: 
        REALM_APP_ID: ${{secrets.REALM_APP_ID}}
      working-directory: ./realmApp
      run: appservices push --remote=REALM_APP_ID
